apiVersion: v1
kind: Service
metadata:
  name: mongo-python-service
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    role: mongo