apiVersion: v1
kind: Service
metadata:
  name: postgres-java-service
  labels:
    name: postgres
spec:
  ports:
    - port: 5432 # Puerto de PostgreSQL
      name: postgres
  clusterIP: None  # Esto permite el acceso directo al servicio sin balanceo de carga
  selector:
    role: postgres  # El mismo valor que utilizaste en el StatefulSet de PostgreSQL
